// Date: 2/18/2016 9:41:16 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.nz.textures.entity;
//TODO: Make the mob for this
public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer torso;
    ModelRenderer head;
  
  public ModelNew()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      leg1 = new ModelRenderer(this, 0, 0);
      leg1.addBox(-2F, -1F, 0F, 4, 12, 4);
      leg1.setRotationPoint(-6F, 13F, 4F);
      leg1.setTextureSize(256, 128);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 16, 16);
      leg2.addBox(-2F, -1F, 0F, 4, 12, 4);
      leg2.setRotationPoint(6F, 13F, 4F);
      leg2.setTextureSize(256, 128);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 0, 16);
      leg3.addBox(-2F, -1F, -4F, 4, 12, 4);
      leg3.setRotationPoint(-6F, 13F, -4F);
      leg3.setTextureSize(256, 128);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 16, 0);
      leg4.addBox(-2F, -1F, -4F, 4, 12, 4);
      leg4.setRotationPoint(6F, 13F, -4F);
      leg4.setTextureSize(256, 128);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      torso = new ModelRenderer(this, 0, 32);
      torso.addBox(-15F, 0F, -11F, 30, 17, 22);
      torso.setRotationPoint(0F, -3F, 0F);
      torso.setTextureSize(256, 128);
      torso.mirror = true;
      setRotation(torso, 0F, 0F, 0F);
      head = new ModelRenderer(this, 20, 74);
      head.addBox(-7F, -5F, -4F, 8, 8, 8);
      head.setRotationPoint(-13F, -2F, 0F);
      head.setTextureSize(256, 128);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    leg1.render(f5);
    leg2.render(f5);
    leg3.render(f5);
    leg4.render(f5);
    torso.render(f5);
    head.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
